import {
  Injectable,
  NotFoundException,
  BadRequestException,
  ConflictException,
} from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { BoardAuthService } from '../../common/services/board-auth.service';
import { AchievementSyncService } from '../../common/services/achievement-sync.service';
import { ErrorMessages } from '../../common/constants/error-messages';
import type { ConditionType } from '@bingo-planner/shared';

@Injectable()
export class ItemService {
  constructor(
    private prisma: PrismaService,
    private boardAuth: BoardAuthService,
    private achievementSync: AchievementSyncService,
  ) {}

  async findOne(boardId: number, itemId: number, userId: number) {
    await this.boardAuth.assertBoardAccess(boardId, userId);
    return this.boardAuth.assertItemBelongsToBoard(itemId, boardId);
  }

  async create(
    boardId: number,
    userId: number,
    dto: {
      title: string;
      position: number;
      description?: string;
      color?: string;
      deadline?: string;
      conditionType?: ConditionType;
      targetCount?: number;
    },
  ) {
    await this.boardAuth.assertBoardOwner(boardId, userId);
    await this.assertActiveBoard(boardId);

    const board = await this.prisma.bingoBoard.findUnique({
      where: { id: boardId },
      select: { size: true },
    });
    if (!board) throw new NotFoundException(ErrorMessages.BOARD_NOT_FOUND);
    const count = await this.prisma.bingoItem.count({ where: { boardId } });
    if (count >= board.size * board.size)
      throw new BadRequestException(ErrorMessages.MAX_ITEMS_REACHED);

    const existing = await this.prisma.bingoItem.findUnique({
      where: { boardId_position: { boardId, position: dto.position } },
    });
    if (existing) throw new ConflictException(ErrorMessages.POSITION_ALREADY_TAKEN);

    const conditionType = dto.conditionType ?? 'ONCE';
    const targetCount = dto.targetCount ?? 1;

    const isRepeat = ['WEEKLY', 'MONTHLY', 'YEARLY'].includes(conditionType);
    let boardForRepeat: { startDate: Date | null; endDate: Date | null } | null = null;
    if (isRepeat) {
      boardForRepeat = await this.prisma.bingoBoard.findUnique({
        where: { id: boardId },
        select: { startDate: true, endDate: true },
      });
      if (!boardForRepeat?.startDate || !boardForRepeat?.endDate)
        throw new BadRequestException(ErrorMessages.REPEAT_REQUIRES_DATES);
    }

    const item = await this.prisma.bingoItem.create({
      data: {
        boardId,
        title: dto.title,
        position: dto.position,
        description: dto.description,
        color: dto.color,
        deadline: dto.deadline ? new Date(dto.deadline) : null,
        conditionType,
        targetCount,
      },
    });

    if (isRepeat && boardForRepeat?.startDate && boardForRepeat?.endDate) {
      const periods = this.splitPeriods(boardForRepeat.startDate, boardForRepeat.endDate, conditionType);
      const checkpointData = periods.map((period, idx) => ({
        bingoItemId: item.id,
        title: period.label,
        isAutoGenerated: true,
        targetCount,
        achievedCount: 0,
        startDate: period.start,
        deadline: period.end,
        sortOrder: idx,
      }));
      await this.prisma.checkpoint.createMany({ data: checkpointData });
    }

    return item;
  }

  private splitPeriods(
    start: Date,
    end: Date,
    conditionType: ConditionType,
  ): { label: string; start: Date; end: Date }[] {
    const periods: { label: string; start: Date; end: Date }[] = [];
    let current = new Date(start);
    let idx = 1;

    while (current < end) {
      let periodEnd: Date;
      let label: string;

      const cy = current.getUTCFullYear();
      const cm = current.getUTCMonth();
      const cd = current.getUTCDate();

      if (conditionType === 'WEEKLY') {
        periodEnd = new Date(Date.UTC(cy, cm, cd + 6));
        if (periodEnd > end) periodEnd = new Date(end);
        label = `${idx}주차 (${this.formatDateUTC(current)}~${this.formatDateUTC(periodEnd)})`;
        periods.push({ label, start: new Date(current), end: periodEnd });
        current = new Date(Date.UTC(cy, cm, cd + 7));
      } else if (conditionType === 'MONTHLY') {
        periodEnd = new Date(Date.UTC(cy, cm + 1, 0));
        if (periodEnd > end) periodEnd = new Date(end);
        label = `${idx}월차 (${this.formatDateUTC(current)}~${this.formatDateUTC(periodEnd)})`;
        periods.push({ label, start: new Date(current), end: periodEnd });
        current = new Date(Date.UTC(cy, cm + 1, 1));
      } else {
        periodEnd = new Date(Date.UTC(cy, 11, 31));
        if (periodEnd > end) periodEnd = new Date(end);
        label = `${idx}년차 (${this.formatDateUTC(current)}~${this.formatDateUTC(periodEnd)})`;
        periods.push({ label, start: new Date(current), end: periodEnd });
        current = new Date(Date.UTC(cy + 1, 0, 1));
      }
      idx++;
    }

    return periods;
  }

  private formatDateUTC(date: Date): string {
    const m = date.getUTCMonth() + 1;
    const d = date.getUTCDate();
    return `${m}/${d}`;
  }

  async update(
    boardId: number,
    itemId: number,
    userId: number,
    dto: {
      title?: string;
      description?: string;
      color?: string;
      deadline?: string;
      position?: number;
      conditionType?: ConditionType;
      targetCount?: number;
    },
  ) {
    await this.boardAuth.assertBoardOwner(boardId, userId);
    await this.assertActiveBoard(boardId);
    const existingItem = await this.boardAuth.assertItemBelongsToBoard(itemId, boardId);

    const isRepeatItem = ['WEEKLY', 'MONTHLY', 'YEARLY'].includes(existingItem.conditionType);
    if (isRepeatItem && (dto.conditionType !== undefined || dto.targetCount !== undefined))
      throw new BadRequestException(ErrorMessages.REPEAT_CONDITION_IMMUTABLE);

    if (dto.position !== undefined) {
      const existing = await this.prisma.bingoItem.findUnique({
        where: { boardId_position: { boardId, position: dto.position } },
      });
      if (existing && existing.id !== itemId)
        throw new ConflictException(ErrorMessages.POSITION_ALREADY_TAKEN);
    }

    return this.prisma.bingoItem.update({
      where: { id: itemId },
      data: {
        title: dto.title,
        description: dto.description,
        color: dto.color,
        position: dto.position,
        conditionType: dto.conditionType,
        targetCount: dto.targetCount,
        deadline: dto.deadline !== undefined ? (dto.deadline ? new Date(dto.deadline) : null) : undefined,
      },
    });
  }

  async remove(boardId: number, itemId: number, userId: number) {
    await this.boardAuth.assertBoardOwner(boardId, userId);
    await this.assertActiveBoard(boardId);
    await this.boardAuth.assertItemBelongsToBoard(itemId, boardId);
    const result = await this.prisma.bingoItem.delete({ where: { id: itemId } });

    await this.achievementSync.syncBoardAchievement(boardId);

    return result;
  }

  async toggleAchieve(boardId: number, itemId: number, userId: number) {
    await this.boardAuth.assertReviewerOnly(boardId, userId);
    const item = await this.boardAuth.assertItemBelongsToBoard(itemId, boardId);
    const isAchieved = !item.isAchieved;
    const updated = await this.prisma.bingoItem.update({
      where: { id: itemId },
      data: {
        isAchieved,
        achievedAt: isAchieved ? new Date() : null,
        achievedBy: isAchieved ? userId : null,
      },
    });

    await this.achievementSync.syncBoardAchievement(boardId);

    return updated;
  }

  private async assertActiveBoard(boardId: number) {
    const board = await this.prisma.bingoBoard.findUnique({
      where: { id: boardId },
      select: { status: true },
    });
    if (!board) throw new NotFoundException(ErrorMessages.BOARD_NOT_FOUND);
    if (board.status !== 'ACTIVE')
      throw new BadRequestException(ErrorMessages.ACTIVE_BOARD_ONLY);
  }

  async swapPositions(
    boardId: number,
    userId: number,
    dto: { positionA: number; positionB: number },
  ) {
    await this.boardAuth.assertBoardOwner(boardId, userId);
    await this.assertActiveBoard(boardId);

    const itemA = await this.prisma.bingoItem.findUnique({
      where: { boardId_position: { boardId, position: dto.positionA } },
    });
    const itemB = await this.prisma.bingoItem.findUnique({
      where: { boardId_position: { boardId, position: dto.positionB } },
    });

    if (!itemA || !itemB)
      throw new NotFoundException(ErrorMessages.SWAP_ITEMS_NOT_FOUND);

    await this.prisma.$transaction([
      this.prisma.bingoItem.update({
        where: { id: itemA.id },
        data: { position: -1 },
      }),
      this.prisma.bingoItem.update({
        where: { id: itemB.id },
        data: { position: dto.positionA },
      }),
      this.prisma.bingoItem.update({
        where: { id: itemA.id },
        data: { position: dto.positionB },
      }),
    ]);

    return { success: true };
  }
}
