import { Test } from '@nestjs/testing';
import {
  NotFoundException,
  BadRequestException,
  ConflictException,
} from '@nestjs/common';
import { ItemService } from './item.service';
import { PrismaService } from '../../prisma/prisma.service';
import { BoardAuthService } from '../../common/services/board-auth.service';
import { AchievementSyncService } from '../../common/services/achievement-sync.service';

describe('ItemService', () => {
  let service: ItemService;
  let prisma: Record<string, any>;
  let boardAuth: Record<string, jest.Mock>;
  let achievementSync: Record<string, jest.Mock>;

  beforeEach(async () => {
    prisma = {
      bingoBoard: {
        findUnique: jest.fn(),
      },
      bingoItem: {
        count: jest.fn(),
        findUnique: jest.fn(),
        create: jest.fn(),
        update: jest.fn(),
        delete: jest.fn(),
      },
      checkpoint: {
        createMany: jest.fn(),
      },
      $transaction: jest.fn().mockResolvedValue(undefined),
    };
    boardAuth = {
      assertBoardOwner: jest.fn().mockResolvedValue(undefined),
      assertBoardAccess: jest.fn().mockResolvedValue(undefined),
      assertItemBelongsToBoard: jest.fn().mockResolvedValue({ id: 1, conditionType: 'ONCE' }),
      assertReviewerOnly: jest.fn().mockResolvedValue(undefined),
    };
    achievementSync = {
      syncBoardAchievement: jest.fn().mockResolvedValue(undefined),
      syncItemAchievement: jest.fn().mockResolvedValue(undefined),
    };

    const module = await Test.createTestingModule({
      providers: [
        ItemService,
        { provide: PrismaService, useValue: prisma },
        { provide: BoardAuthService, useValue: boardAuth },
        { provide: AchievementSyncService, useValue: achievementSync },
      ],
    }).compile();

    service = module.get(ItemService);
  });

  describe('create', () => {
    const baseDto = { title: 'Item', position: 0 };

    beforeEach(() => {
      // Active board
      prisma.bingoBoard.findUnique
        .mockResolvedValueOnce({ status: 'ACTIVE' })   // assertActiveBoard
        .mockResolvedValueOnce({ size: 3 });            // size check
      prisma.bingoItem.count.mockResolvedValue(0);
      prisma.bingoItem.findUnique.mockResolvedValue(null); // no position conflict
      prisma.bingoItem.create.mockResolvedValue({ id: 1, ...baseDto, conditionType: 'ONCE', targetCount: 1 });
    });

    it('기본 아이템 생성', async () => {
      const result = await service.create(1, 1, baseDto);
      expect(result.id).toBe(1);
      expect(prisma.bingoItem.create).toHaveBeenCalled();
    });

    it('최대 아이템 수 초과 → BadRequestException', async () => {
      prisma.bingoItem.count.mockResolvedValue(9); // 3x3 = 9
      await expect(service.create(1, 1, baseDto)).rejects.toThrow(BadRequestException);
    });

    it('포지션 중복 → ConflictException', async () => {
      prisma.bingoItem.findUnique.mockResolvedValue({ id: 99 });
      await expect(service.create(1, 1, baseDto)).rejects.toThrow(ConflictException);
    });

    it('반복 아이템(WEEKLY) → 체크포인트 자동생성', async () => {
      prisma.bingoBoard.findUnique
        .mockReset()
        .mockResolvedValueOnce({ status: 'ACTIVE' })
        .mockResolvedValueOnce({ size: 3 })
        .mockResolvedValueOnce({ startDate: new Date('2025-01-01'), endDate: new Date('2025-01-21') });
      prisma.bingoItem.count.mockResolvedValue(0);
      prisma.bingoItem.findUnique.mockResolvedValue(null);
      prisma.bingoItem.create.mockResolvedValue({ id: 10, title: 'Weekly', conditionType: 'WEEKLY', targetCount: 1 });

      await service.create(1, 1, { ...baseDto, conditionType: 'WEEKLY' });
      expect(prisma.checkpoint.createMany).toHaveBeenCalled();
      const data = prisma.checkpoint.createMany.mock.calls[0][0].data;
      expect(data.length).toBe(3); // 3 weeks
      expect(data[0].isAutoGenerated).toBe(true);
    });

    it('반복 아이템: 보드에 날짜 없으면 → BadRequestException', async () => {
      prisma.bingoBoard.findUnique
        .mockReset()
        .mockResolvedValueOnce({ status: 'ACTIVE' })
        .mockResolvedValueOnce({ size: 3 })
        .mockResolvedValueOnce({ startDate: null, endDate: null });
      prisma.bingoItem.count.mockResolvedValue(0);
      prisma.bingoItem.findUnique.mockResolvedValue(null);

      await expect(service.create(1, 1, { ...baseDto, conditionType: 'MONTHLY' })).rejects.toThrow(BadRequestException);
    });
  });

  describe('update', () => {
    it('반복 아이템 conditionType 변경 불가', async () => {
      prisma.bingoBoard.findUnique.mockResolvedValue({ status: 'ACTIVE' });
      boardAuth.assertItemBelongsToBoard.mockResolvedValue({ id: 1, conditionType: 'WEEKLY' });

      await expect(
        service.update(1, 1, 1, { conditionType: 'MONTHLY' }),
      ).rejects.toThrow(BadRequestException);
    });
  });

  describe('swapPositions', () => {
    it('포지션 교환 트랜잭션', async () => {
      prisma.bingoBoard.findUnique.mockResolvedValue({ status: 'ACTIVE' });
      prisma.bingoItem.findUnique
        .mockResolvedValueOnce({ id: 1, position: 0 })
        .mockResolvedValueOnce({ id: 2, position: 1 });

      const result = await service.swapPositions(1, 1, { positionA: 0, positionB: 1 });
      expect(prisma.$transaction).toHaveBeenCalled();
      expect(result).toEqual({ success: true });
    });

    it('아이템 없으면 → NotFoundException', async () => {
      prisma.bingoBoard.findUnique.mockResolvedValue({ status: 'ACTIVE' });
      prisma.bingoItem.findUnique
        .mockResolvedValueOnce(null)
        .mockResolvedValueOnce({ id: 2 });

      await expect(
        service.swapPositions(1, 1, { positionA: 0, positionB: 1 }),
      ).rejects.toThrow(NotFoundException);
    });
  });
});
