import { useState } from 'react';
import type { Checkpoint } from '@/types';

interface CheckpointCardProps {
  checkpoint: Checkpoint;
  isOwner: boolean;
  isReviewer: boolean;
  isExpanded: boolean;
  onToggleAchieve: (cpId: number) => void;
  onEdit: (cpId: number, title: string) => Promise<void>;
  onDelete: (cpId: number) => void;
  onExpand: (cpId: number) => void;
  children?: React.ReactNode;
}

export default function CheckpointCard({
  checkpoint: cp,
  isOwner,
  isReviewer,
  isExpanded,
  onToggleAchieve,
  onEdit,
  onDelete,
  onExpand,
  children,
}: CheckpointCardProps) {
  const [editing, setEditing] = useState(false);
  const [editTitle, setEditTitle] = useState(cp.title);

  async function handleSave() {
    if (!editTitle.trim()) return;
    await onEdit(cp.id, editTitle.trim());
    setEditing(false);
  }

  return (
    <div className="bg-surface1 rounded-[var(--radius-card)] shadow overflow-hidden">
      <div className="flex items-center gap-3 px-4 py-3">
        {cp.isAutoGenerated ? (
          <div className="w-5 h-5 flex-shrink-0" />
        ) : isReviewer ? (
          <button
            onClick={() => onToggleAchieve(cp.id)}
            className={`w-5 h-5 flex-shrink-0 rounded border-2 flex items-center justify-center transition ${
              cp.isAchieved
                ? 'bg-primary border-primary text-white'
                : 'border-border hover:border-primary'
            }`}
          >
            {cp.isAchieved && (
              <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" strokeWidth={3} stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="m4.5 12.75 6 6 9-13.5" />
              </svg>
            )}
          </button>
        ) : (
          <div className={`w-5 h-5 flex-shrink-0 rounded border-2 flex items-center justify-center ${
            cp.isAchieved ? 'bg-primary border-primary text-white' : 'border-border'
          }`}>
            {cp.isAchieved && (
              <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" strokeWidth={3} stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="m4.5 12.75 6 6 9-13.5" />
              </svg>
            )}
          </div>
        )}

        <div className="flex-1 min-w-0">
          {editing ? (
            <div className="flex gap-2">
              <input
                type="text"
                value={editTitle}
                onChange={(e) => setEditTitle(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSave()}
                className="flex-1 px-2 py-1 bg-surface2 border border-border rounded-[var(--radius-control)] text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary"
              />
              <button onClick={handleSave} className="text-xs text-primary hover:text-primary/80">저장</button>
              <button onClick={() => setEditing(false)} className="text-xs text-muted hover:text-text">취소</button>
            </div>
          ) : (
            <div>
              <p className={`text-sm font-medium ${cp.isAchieved ? 'line-through text-muted' : 'text-text'}`}>
                {cp.title}
              </p>
              {cp.isAutoGenerated && (
                <div className="flex items-center gap-1.5 mt-1">
                  <div className="flex-1 h-1.5 bg-surface2 rounded-full overflow-hidden max-w-[120px]">
                    <div
                      className="h-full bg-primary rounded-full transition-all"
                      style={{ width: `${Math.min(100, (cp.achievedCount / cp.targetCount) * 100)}%` }}
                    />
                  </div>
                  <span className="text-xs text-muted">{cp.achievedCount}/{cp.targetCount}</span>
                </div>
              )}
              {(cp.startDate || cp.deadline) && (
                <p className="text-[10px] text-muted mt-0.5">
                  {cp.startDate ? cp.startDate.split('T')[0] : ''} ~ {cp.deadline ? cp.deadline.split('T')[0] : ''}
                </p>
              )}
            </div>
          )}
        </div>

        <div className="flex items-center gap-2 flex-shrink-0">
          {isOwner && !cp.isAutoGenerated && !editing && (
            <>
              <button
                onClick={() => { setEditing(true); setEditTitle(cp.title); }}
                className="text-xs text-muted hover:text-primary"
              >수정</button>
              <button
                onClick={() => onDelete(cp.id)}
                className="text-xs text-muted hover:text-danger"
              >삭제</button>
            </>
          )}
          <button
            onClick={() => onExpand(cp.id)}
            className="text-xs text-primary hover:text-primary/80"
          >
            {isExpanded ? '접기' : '기록'}
          </button>
        </div>
      </div>

      {isExpanded && children && (
        <div className="border-t border-border px-4 py-3">
          {children}
        </div>
      )}
    </div>
  );
}
