import { Injectable } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';

export interface TodoItem {
  type: 'ITEM' | 'CHECKPOINT';
  id: number;
  title: string;
  deadline: string;
  boardId: number;
  itemId: number;
  boardTitle: string;
  isAchieved: boolean;
}

@Injectable()
export class TodoService {
  constructor(private prisma: PrismaService) {}

  async getTodos(userId: number): Promise<TodoItem[]> {
    // 유저가 접근 가능한 보드 조회
    const boards = await this.prisma.bingoBoard.findMany({
      where: {
        ownerId: userId,
      },
      select: { id: true, title: true },
    });

    const boardMap = new Map(boards.map((b) => [b.id, b.title]));
    const boardIds = boards.map((b) => b.id);
    if (boardIds.length === 0) return [];

    // 미달성 + deadline 있는 아이템
    const items = await this.prisma.bingoItem.findMany({
      where: {
        boardId: { in: boardIds },
        isAchieved: false,
        deadline: { not: null },
      },
      select: {
        id: true,
        title: true,
        deadline: true,
        boardId: true,
        isAchieved: true,
      },
      orderBy: { deadline: 'asc' },
    });

    // 미달성 + deadline 있는 체크포인트
    const checkpoints = await this.prisma.checkpoint.findMany({
      where: {
        bingoItem: { boardId: { in: boardIds } },
        isAchieved: false,
        deadline: { not: null },
      },
      select: {
        id: true,
        title: true,
        deadline: true,
        isAchieved: true,
        bingoItem: { select: { id: true, boardId: true } },
      },
      orderBy: { deadline: 'asc' },
    });

    const todos: TodoItem[] = [];

    for (const item of items) {
      todos.push({
        type: 'ITEM',
        id: item.id,
        title: item.title,
        deadline: item.deadline!.toISOString().slice(0, 10),
        boardId: item.boardId,
        itemId: item.id,
        boardTitle: boardMap.get(item.boardId) ?? '',
        isAchieved: item.isAchieved,
      });
    }

    for (const cp of checkpoints) {
      todos.push({
        type: 'CHECKPOINT',
        id: cp.id,
        title: cp.title,
        deadline: cp.deadline!.toISOString().slice(0, 10),
        boardId: cp.bingoItem.boardId,
        itemId: cp.bingoItem.id,
        boardTitle: boardMap.get(cp.bingoItem.boardId) ?? '',
        isAchieved: cp.isAchieved,
      });
    }

    // deadline 오름차순 정렬
    todos.sort((a, b) => a.deadline.localeCompare(b.deadline));

    return todos;
  }

  async getTodoTree(userId: number) {
    const boards = await this.prisma.bingoBoard.findMany({
      where: {
        ownerId: userId,
      },
      select: {
        id: true,
        title: true,
        items: {
          where: { isAchieved: false },
          select: {
            id: true,
            title: true,
            conditionType: true,
            targetCount: true,
            isAchieved: true,
            deadline: true,
            checkpoints: {
              where: { isAchieved: false },
              select: {
                id: true,
                title: true,
                isAchieved: true,
                isAutoGenerated: true,
                targetCount: true,
                achievedCount: true,
                startDate: true,
                deadline: true,
                sortOrder: true,
              },
              orderBy: { sortOrder: 'asc' },
            },
          },
          orderBy: { position: 'asc' },
        },
      },
    });

    // 체크포인트가 하나라도 있는 아이템, 아이템이 하나라도 있는 보드만 반환
    return boards
      .map((board) => ({
        ...board,
        items: board.items
          .filter((item) => item.checkpoints.length > 0)
          .map((item) => ({
            ...item,
            deadline: item.deadline?.toISOString().slice(0, 10) ?? null,
            checkpoints: item.checkpoints.map((cp) => ({
              ...cp,
              startDate: cp.startDate?.toISOString().slice(0, 10) ?? null,
              deadline: cp.deadline?.toISOString().slice(0, 10) ?? null,
            })),
          })),
      }))
      .filter((board) => board.items.length > 0);
  }
}
