-- AlterTable
ALTER TABLE "checkpoints" ADD COLUMN     "achievedCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "startDate" DATE,
ADD COLUMN     "targetCount" INTEGER NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "progress_records" ADD COLUMN     "reviewedAt" TIMESTAMP(3),
ADD COLUMN     "reviewedBy" INTEGER,
ADD COLUMN     "status" VARCHAR(20) NOT NULL DEFAULT 'PENDING';
