import {
  Injectable,
  BadRequestException,
} from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { NotificationService } from '../notification/notification.service';
import { BoardAuthService } from '../../common/services/board-auth.service';
import { AchievementSyncService } from '../../common/services/achievement-sync.service';
import { ErrorMessages } from '../../common/constants/error-messages';

@Injectable()
export class CheckpointService {
  constructor(
    private prisma: PrismaService,
    private notificationService: NotificationService,
    private boardAuth: BoardAuthService,
    private achievementSync: AchievementSyncService,
  ) {}

  async findAll(boardId: number, itemId: number, userId: number) {
    await this.boardAuth.assertBoardAccess(boardId, userId);
    await this.boardAuth.assertItemBelongsToBoard(itemId, boardId);
    return this.prisma.checkpoint.findMany({
      where: { bingoItemId: itemId },
      orderBy: { sortOrder: 'asc' },
    });
  }

  async create(
    boardId: number,
    itemId: number,
    userId: number,
    dto: { title: string; description?: string; deadline?: string; sortOrder?: number },
  ) {
    await this.boardAuth.assertBoardOwner(boardId, userId);
    await this.boardAuth.assertItemBelongsToBoard(itemId, boardId);
    return this.prisma.checkpoint.create({
      data: {
        bingoItemId: itemId,
        title: dto.title,
        description: dto.description,
        deadline: dto.deadline ? new Date(dto.deadline) : null,
        sortOrder: dto.sortOrder ?? 0,
      },
    });
  }

  async update(
    boardId: number,
    itemId: number,
    checkpointId: number,
    userId: number,
    dto: { title?: string; description?: string; deadline?: string; sortOrder?: number },
  ) {
    await this.boardAuth.assertBoardOwner(boardId, userId);
    await this.boardAuth.assertItemBelongsToBoard(itemId, boardId);
    const checkpoint = await this.boardAuth.assertCheckpointBelongsToItem(checkpointId, itemId);
    if (checkpoint.isAutoGenerated)
      throw new BadRequestException(ErrorMessages.AUTO_CHECKPOINT_NO_EDIT);
    return this.prisma.checkpoint.update({
      where: { id: checkpointId },
      data: {
        title: dto.title,
        description: dto.description,
        deadline: dto.deadline !== undefined ? (dto.deadline ? new Date(dto.deadline) : null) : undefined,
        sortOrder: dto.sortOrder,
      },
    });
  }

  async remove(boardId: number, itemId: number, checkpointId: number, userId: number) {
    await this.boardAuth.assertBoardOwner(boardId, userId);
    await this.boardAuth.assertItemBelongsToBoard(itemId, boardId);
    const checkpoint = await this.boardAuth.assertCheckpointBelongsToItem(checkpointId, itemId);
    if (checkpoint.isAutoGenerated)
      throw new BadRequestException(ErrorMessages.AUTO_CHECKPOINT_NO_DELETE);
    return this.prisma.checkpoint.delete({ where: { id: checkpointId } });
  }

  async toggleAchieve(boardId: number, itemId: number, checkpointId: number, userId: number) {
    await this.boardAuth.assertReviewerOnly(boardId, userId);
    await this.boardAuth.assertItemBelongsToBoard(itemId, boardId);
    const checkpoint = await this.boardAuth.assertCheckpointBelongsToItem(checkpointId, itemId);
    if (checkpoint.isAutoGenerated)
      throw new BadRequestException(ErrorMessages.AUTO_CHECKPOINT_REVIEW_ONLY);
    const isAchieved = !checkpoint.isAchieved;
    const updated = await this.prisma.checkpoint.update({
      where: { id: checkpointId },
      data: {
        isAchieved,
        achievedAt: isAchieved ? new Date() : null,
        achievedBy: isAchieved ? userId : null,
      },
    });

    if (isAchieved) {
      const board = await this.prisma.bingoBoard.findUnique({
        where: { id: boardId },
        select: { ownerId: true },
      });
      if (board && board.ownerId !== userId) {
        await this.notificationService.createNotification(
          board.ownerId,
          'ACHIEVEMENT',
          'CHECKPOINT',
          checkpointId,
          `'${checkpoint.title}' 체크포인트가 달성되었습니다.`,
        );
      }
    }

    await this.achievementSync.syncItemAchievement(itemId, userId);

    return updated;
  }
}
