import { Test } from '@nestjs/testing';
import { BadRequestException } from '@nestjs/common';
import { CheckpointService } from './checkpoint.service';
import { PrismaService } from '../../prisma/prisma.service';
import { NotificationService } from '../notification/notification.service';
import { BoardAuthService } from '../../common/services/board-auth.service';
import { AchievementSyncService } from '../../common/services/achievement-sync.service';

describe('CheckpointService', () => {
  let service: CheckpointService;
  let prisma: Record<string, any>;
  let boardAuth: Record<string, jest.Mock>;
  let achievementSync: Record<string, jest.Mock>;
  let notificationService: Record<string, jest.Mock>;

  beforeEach(async () => {
    prisma = {
      checkpoint: {
        findMany: jest.fn(),
        create: jest.fn(),
        update: jest.fn(),
        delete: jest.fn(),
      },
      bingoBoard: {
        findUnique: jest.fn(),
      },
    };
    boardAuth = {
      assertBoardOwner: jest.fn().mockResolvedValue(undefined),
      assertBoardAccess: jest.fn().mockResolvedValue(undefined),
      assertItemBelongsToBoard: jest.fn().mockResolvedValue({ id: 1 }),
      assertCheckpointBelongsToItem: jest.fn(),
      assertReviewerOnly: jest.fn().mockResolvedValue(undefined),
    };
    achievementSync = {
      syncItemAchievement: jest.fn().mockResolvedValue(undefined),
    };
    notificationService = {
      createNotification: jest.fn().mockResolvedValue(undefined),
    };

    const module = await Test.createTestingModule({
      providers: [
        CheckpointService,
        { provide: PrismaService, useValue: prisma },
        { provide: NotificationService, useValue: notificationService },
        { provide: BoardAuthService, useValue: boardAuth },
        { provide: AchievementSyncService, useValue: achievementSync },
      ],
    }).compile();

    service = module.get(CheckpointService);
  });

  describe('update', () => {
    it('자동생성 체크포인트 수정 → 에러', async () => {
      boardAuth.assertCheckpointBelongsToItem.mockResolvedValue({
        id: 1, isAutoGenerated: true,
      });

      await expect(
        service.update(1, 1, 1, 1, { title: 'new' }),
      ).rejects.toThrow(BadRequestException);
    });

    it('수동 체크포인트 수정 성공', async () => {
      boardAuth.assertCheckpointBelongsToItem.mockResolvedValue({
        id: 1, isAutoGenerated: false,
      });
      prisma.checkpoint.update.mockResolvedValue({ id: 1, title: 'new' });

      const result = await service.update(1, 1, 1, 1, { title: 'new' });
      expect(result.title).toBe('new');
    });
  });

  describe('remove', () => {
    it('자동생성 체크포인트 삭제 → 에러', async () => {
      boardAuth.assertCheckpointBelongsToItem.mockResolvedValue({
        id: 1, isAutoGenerated: true,
      });

      await expect(service.remove(1, 1, 1, 1)).rejects.toThrow(BadRequestException);
    });

    it('수동 체크포인트 삭제 성공', async () => {
      boardAuth.assertCheckpointBelongsToItem.mockResolvedValue({
        id: 1, isAutoGenerated: false,
      });
      prisma.checkpoint.delete.mockResolvedValue({ id: 1 });

      await service.remove(1, 1, 1, 1);
      expect(prisma.checkpoint.delete).toHaveBeenCalledWith({ where: { id: 1 } });
    });
  });

  describe('toggleAchieve', () => {
    it('자동생성 체크포인트 토글 불가', async () => {
      boardAuth.assertCheckpointBelongsToItem.mockResolvedValue({
        id: 1, isAutoGenerated: true, isAchieved: false, title: 'auto-cp',
      });

      await expect(service.toggleAchieve(1, 1, 1, 1)).rejects.toThrow(BadRequestException);
    });

    it('수동 체크포인트 토글 → 달성 동기화 호출', async () => {
      boardAuth.assertCheckpointBelongsToItem.mockResolvedValue({
        id: 1, isAutoGenerated: false, isAchieved: false, title: 'manual-cp',
      });
      prisma.checkpoint.update.mockResolvedValue({ id: 1, isAchieved: true });
      prisma.bingoBoard.findUnique.mockResolvedValue({ ownerId: 99 });

      await service.toggleAchieve(1, 1, 1, 1);
      expect(prisma.checkpoint.update).toHaveBeenCalled();
      expect(achievementSync.syncItemAchievement).toHaveBeenCalledWith(1, 1);
    });

    it('리뷰어만 가능 (assertReviewerOnly 호출 확인)', async () => {
      boardAuth.assertCheckpointBelongsToItem.mockResolvedValue({
        id: 1, isAutoGenerated: false, isAchieved: false, title: 'cp',
      });
      prisma.checkpoint.update.mockResolvedValue({ id: 1, isAchieved: true });
      prisma.bingoBoard.findUnique.mockResolvedValue({ ownerId: 1 });

      await service.toggleAchieve(1, 1, 1, 5);
      expect(boardAuth.assertReviewerOnly).toHaveBeenCalledWith(1, 5);
    });
  });
});
