import type { BoardStatus, ConditionType, MemberRole, MemberStatus, RecordStatus } from '@bingo-planner/shared';

// Board list page
export interface Board {
  id: number;
  title: string;
  size: number;
  status: BoardStatus;
  role: string;
  progress: { achieved: number; total: number };
  createdAt: string;
}

// Board detail page
export interface BingoItem {
  id: number;
  title: string;
  description: string | null;
  position: number;
  color: string | null;
  conditionType: ConditionType;
  targetCount: number;
  isAchieved: boolean;
  achievedAt: string | null;
}

export interface Member {
  id: number;
  userId: number;
  role: MemberRole;
  status: MemberStatus;
  user: { id: number; nickname: string; profileImageUrl: string | null };
}

export interface BoardDetail {
  id: number;
  title: string;
  description: string | null;
  size: number;
  status: BoardStatus;
  startDate: string | null;
  endDate: string | null;
  ownerId: number;
  owner: { id: number; nickname: string; profileImageUrl: string | null };
  members: Member[];
  items: BingoItem[];
  createdAt: string;
}

// Item detail page
export interface ItemDetail {
  id: number;
  boardId: number;
  title: string;
  description: string | null;
  position: number;
  color: string | null;
  deadline: string | null;
  conditionType: ConditionType;
  targetCount: number;
  isAchieved: boolean;
  achievedAt: string | null;
}

export interface Checkpoint {
  id: number;
  title: string;
  description: string | null;
  deadline: string | null;
  sortOrder: number;
  isAchieved: boolean;
  achievedAt: string | null;
  isAutoGenerated: boolean;
  targetCount: number;
  achievedCount: number;
  startDate: string | null;
}

export interface ProgressRecord {
  id: number;
  content: string | null;
  imageUrls: string[];
  recordedAt: string;
  status: RecordStatus;
  reviewedBy: number | null;
  reviewedAt: string | null;
  author: { id: number; nickname: string; profileImageUrl: string | null };
}

export interface BoardMember {
  userId: number;
  role: MemberRole;
  status: MemberStatus;
}

export interface BoardInfo {
  ownerId: number;
  members: BoardMember[];
}

export interface Comment {
  id: number;
  content: string;
  createdAt: string;
  author: { id: number; nickname: string; profileImageUrl: string | null };
}

// Notification page
export interface Notification {
  id: number;
  type: string;
  targetType: string;
  targetId: number;
  message: string;
  isRead: boolean;
  createdAt: string;
  boardId: number | null;
  itemId: number | null;
  checkpointId: number | null;
}

// Calendar page
export interface CalendarEvent {
  date: string;
  type: 'ITEM' | 'CHECKPOINT';
  id: number;
  title: string;
  boardId: number;
  itemId: number;
  itemTitle: string;
  isAchieved: boolean;
}

// Todos page
export interface TodoCheckpoint {
  id: number;
  title: string;
  isAchieved: boolean;
  isAutoGenerated: boolean;
  targetCount: number;
  achievedCount: number;
  startDate: string | null;
  deadline: string | null;
  sortOrder: number;
}

export interface TodoBingoItem {
  id: number;
  title: string;
  conditionType: ConditionType;
  targetCount: number;
  isAchieved: boolean;
  deadline: string | null;
  checkpoints: TodoCheckpoint[];
}

export interface TodoBoard {
  id: number;
  title: string;
  items: TodoBingoItem[];
}
